# Generated by Django 4.2 on 2026-04-20 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AptitudeTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("quantitative", "Quantitative Aptitude"),
                            ("data_interpretation", "Data Interpretation"),
                            ("logical_reasoning", "Logical Reasoning"),
                            ("verbal_ability", "Verbal Ability"),
                            ("computer_aptitude", "Computer Aptitude"),
                            ("general_aptitude", "General Aptitude"),
                        ],
                        default="quantitative",
                        max_length=50,
                    ),
                ),
                (
                    "category_label",
                    models.CharField(default="Quantitative Aptitude", max_length=100),
                ),
                ("icon", models.CharField(default="📘", max_length=10)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                        ],
                        default="Beginner",
                        max_length=20,
                    ),
                ),
                ("has_quiz", models.BooleanField(default=True)),
                (
                    "definition",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Aptitude Topic",
                "verbose_name_plural": "Aptitude Topics",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AptitudeQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("option_a", models.CharField(max_length=300)),
                ("option_b", models.CharField(max_length=300)),
                ("option_c", models.CharField(max_length=300)),
                ("option_d", models.CharField(max_length=300)),
                ("correct_answer", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="aptitude.aptitudetopic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aptitude Question",
                "verbose_name_plural": "Aptitude Questions",
                "ordering": ["id"],
            },
        ),
    ]
