# Generated by Django 4.2 on 2026-04-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0002_interviewsession_hr_avg_score_evaluationresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationresult",
            name="report_pdf",
            field=models.FileField(
                blank=True,
                help_text="Cached PDF report generated by reportlab",
                null=True,
                upload_to="reports/",
            ),
        ),
        migrations.AlterField(
            model_name="interviewsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("abandoned", "Abandoned"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
